services:
  vid-transcript:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Optional: Whisper model size
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-base}
      # Server configuration
      - HOST=0.0.0.0
      - PORT=8000
    # volumes:
      # Mount temp directory to inspect downloaded files  
      # - ./temp:/app/temp
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"   # Frontend at http://<server>:8080 (Caddy/NGINX can reverse-proxy the domain)
    volumes:
      - ./static:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - vid-transcript
